# Generated by Django 3.2.3 on 2021-06-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foods', models.TextField()),
                ('Ichimliklar', models.TextField()),
                ('salatlar', models.TextField()),
                ('shirinliklar', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Foydalanuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('number', models.IntegerField()),
                ('manzili', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Galereya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('img_abaut', models.TextField()),
                ('text_abaot', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Restourant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('telefon_raqam', models.IntegerField()),
                ('odamlar_soni', models.TextField()),
                ('sana', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Telebashniya1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('images', models.ImageField(upload_to='')),
            ],
        ),
    ]
